/**
 * Valid companion organism identifiers with character archetypes.
 */
export type OrganismId =
  | 'Sarge'
  | 'waifu'
  | 'sherlock'
  | 'kuro'
  | 'sensei'
  | 'byte'
  | 'pixel'
  | 'ufo';

/**
 * How the companion chooses to respond to a judged moment.
 * `observe` is a deliberate decision to stay silent.
 */
export type InterventionKind = 'observe' | 'nudge' | 'callout' | 'reset';

/**
 * Append-only session episode — the raw material of the memory loop.
 * Interventions open episodes; outcome observations close them.
 */
export interface SessionEpisode {
  id: string;
  ts: number;
  type: 'divergence' | 'on_task' | 'intervention' | 'outcome' | 'milestone';
  domain?: string;
  detail: string;
  goalTitle?: string;
  intervention?: {
    kind: InterventionKind;
    level: number;
    remark?: string;
  };
  outcome?: {
    returnedWithinMin?: number;
    effective?: boolean;
  };
}

/**
 * What the companion has learned about how its human focuses. Rules keep the live stats
 * fresh; the nightly Psychologist distills `lessons`. Mirrored to sync storage
 * (best-effort) so reinstallations retain identity.
 */
export interface FocusProfile {
  focusWindows: Array<{ hour: number; score: number }>;
  topDistractions: Array<{ domain: string; count: number }>;
  interventionEffectiveness: Record<string, { sent: number; effective: number }>;
  lessons: string[];
  updatedAt: number;
}

/**
 * Visual and behavioral mood states of the companion organism.
 */
export type OrganismState =
  | 'idle'
  | 'watching'
  | 'peek'
  | 'curious'
  | 'confused'
  | 'suspicious'
  | 'annoyed'
  | 'celebrating'
  | 'sleeping'
  | 'shocked'
  | 'thinking'
  | 'wandering'
  | 'hidden';

/**
 * Focus sprint data model supporting both target countdowns and continuous open-ended flow.
 */
export interface FocusSprint {
  goal: string;
  targetMinutes: number;
  startedAt: number;
  status: 'idle' | 'active' | 'paused' | 'completed';
  isContinuousFlow?: boolean;
}

/**
 * Dynamically structured goal or milestone item synthesized by the AI agent.
 */
export interface DecomposedGoal {
  id: string;
  title: string;
  category: string;
  estimatedMinutes?: number;
  isActive: boolean;
  completed: boolean;
  createdAt: number;
  completedAt?: number;
}

/**
 * Contextual smart note taken by the user, anchored to a web page and focus goal.
 */
export interface SmartPageNote {
  id: string;
  content: string;
  url: string;
  domain: string;
  pageTitle: string;
  snippet?: string;
  goalId?: string;
  goalTitle?: string;
  companionId: OrganismId;
  timestamp: number;
}

/**
 * Single focus session segment recorded in the daily diary.
 */
export interface DailyFocusSession {
  id: string;
  goalTitle: string;
  startedAt: number;
  endedAt: number;
  durationMinutes: number;
  domains: string[];
  notesCount: number;
  divergenceCount: number;
}

/**
 * In-character daily reflection and advice generated by the companion.
 */
export interface CompanionDailyReflection {
  companionId: OrganismId;
  score: number; // 0-10
  headline: string;
  summary: string;
  advice: string;
  timestamp: number;
}

/**
 * Complete daily focus diary aggregating sessions, notes, metrics, and character reflections.
 */
export interface DailyDiary {
  date: string; // YYYY-MM-DD
  totalFocusMinutes: number;
  totalDetours: number;
  completedGoalsCount: number;
  sessions: DailyFocusSession[];
  notes: SmartPageNote[];
  topDomains: { domain: string; minutes: number }[];
  companionReflection?: CompanionDailyReflection;
}

/**
 * User account profile.
 */
export interface UserProfile {
  id: string;
  email: string;
  name?: string;
  plan: 'free' | 'pro';
  createdAt: number;
}

/**
 * Semantic context extracted from a single web page tab.
 */
export interface BrowsingBreadcrumb {
  url: string;
  domain: string;
  title: string;
  headings: string[];
  metaDescription?: string;
  textExcerpt: string;
  dwellSeconds: number;
  scrollDepthPercent: number;
  isMediaPlaying: boolean;
  timestamp: number;
}

/**
 * Rolling timeline of user browsing events over time.
 */
export interface RollingTimelineEntry {
  domain: string;
  title: string;
  dwellSeconds: number;
  scrollDepthPercent: number;
  isMediaPlaying: boolean;
  timestamp: number;
}

/**
 * Full narrative context payload provided to the AI focus agent.
 */
export interface RollingHistoryWindow {
  sprint: FocusSprint;
  goals?: DecomposedGoal[];
  notes?: SmartPageNote[];
  companionId: OrganismId;
  currentTab: BrowsingBreadcrumb;
  timeline: RollingTimelineEntry[];
  elapsedSprintMinutes: number;
  totalDivergenceCountToday?: number;
  localTime?: string;
  isContinuousFlow?: boolean;
}

/**
 * AI Agent's classification of user activity alignment.
 */
export type AgentFocusStatus =
  | 'on_task'
  | 'exploring_tangent'
  | 'distracted'
  | 'resting_or_idle'
  | 'goal_completed';

/**
 * Structured output generated by the AI evaluation agent.
 */
export interface EvaluationResult {
  status: AgentFocusStatus;
  divergenceScore: number;
  mood: OrganismState;
  remark: string;
  visualEffect: 'none' | 'vignette' | 'screen_shake' | 'confetti';
  soundReaction: 'none' | 'chirp' | 'alert' | 'celebrate' | 'sigh';
  reasoning: string;
  /** Chosen response. `observe` means the agent deliberately stays silent. */
  intervention: InterventionKind;
  /** One-line memory worth carrying into the diary/profile. */
  noteForDiary?: string;
  /** Suggested escalation adjustment, typically -1..+1 per judgment. */
  escalationDelta?: number;
}


