/**
 * Valid companion organism identifiers with character archetypes.
 */
export type OrganismId =
  | 'goggins'
  | 'waifu'
  | 'sherlock'
  | 'kuro'
  | 'sensei';

/**
 * Visual and behavioral mood states of the companion organism.
 */
export type OrganismState =
  | 'idle'
  | 'watching'
  | 'peek'
  | 'curious'
  | 'confused'
  | 'suspicious'
  | 'annoyed'
  | 'celebrating'
  | 'sleeping'
  | 'shocked'
  | 'thinking'
  | 'wandering'
  | 'hidden';

/**
 * Focus sprint data model supporting both target countdowns and continuous open-ended flow.
 */
export interface FocusSprint {
  goal: string;
  targetMinutes: number;
  startedAt: number;
  status: 'idle' | 'active' | 'paused' | 'completed';
  isContinuousFlow?: boolean;
}

/**
 * Dynamically structured goal or milestone item synthesized by the AI agent.
 */
export interface DecomposedGoal {
  id: string;
  title: string;
  category: string;
  estimatedMinutes?: number;
  isActive: boolean;
  completed: boolean;
  createdAt: number;
  completedAt?: number;
}

/**
 * Contextual smart note taken by the user, anchored to a web page and focus goal.
 */
export interface SmartPageNote {
  id: string;
  content: string;
  url: string;
  domain: string;
  pageTitle: string;
  snippet?: string;
  goalId?: string;
  goalTitle?: string;
  companionId: OrganismId;
  timestamp: number;
}

/**
 * Single focus session segment recorded in the daily diary.
 */
export interface DailyFocusSession {
  id: string;
  goalTitle: string;
  startedAt: number;
  endedAt: number;
  durationMinutes: number;
  domains: string[];
  notesCount: number;
  divergenceCount: number;
}

/**
 * In-character daily reflection and advice generated by the companion.
 */
export interface CompanionDailyReflection {
  companionId: OrganismId;
  score: number; // 0-10
  headline: string;
  summary: string;
  advice: string;
  timestamp: number;
}

/**
 * Complete daily focus diary aggregating sessions, notes, metrics, and character reflections.
 */
export interface DailyDiary {
  date: string; // YYYY-MM-DD
  totalFocusMinutes: number;
  totalDetours: number;
  completedGoalsCount: number;
  sessions: DailyFocusSession[];
  notes: SmartPageNote[];
  topDomains: { domain: string; minutes: number }[];
  companionReflection?: CompanionDailyReflection;
}

/**
 * AI SDK execution telemetry trace capturing latency, token usage, and thinking traces.
 */
export interface AiTelemetryTrace {
  id: string;
  timestamp: number;
  functionId: string;
  provider: string;
  model: string;
  latencyMs: number;
  promptTokens: number;
  completionTokens: number;
  totalTokens: number;
  goal: string;
  activeDomain: string;
  activeTitle: string;
  status: AgentFocusStatus;
  mood: OrganismState;
  remark?: string;
  reasoning?: string;
}

/**
 * User account profile.
 */
export interface UserProfile {
  id: string;
  email: string;
  name?: string;
  plan: 'free' | 'pro';
  createdAt: number;
}

/**
 * Semantic context extracted from a single web page tab.
 */
export interface BrowsingBreadcrumb {
  url: string;
  domain: string;
  title: string;
  headings: string[];
  metaDescription?: string;
  textExcerpt: string;
  dwellSeconds: number;
  scrollDepthPercent: number;
  isMediaPlaying: boolean;
  timestamp: number;
}

/**
 * Rolling timeline of user browsing events over time.
 */
export interface RollingTimelineEntry {
  domain: string;
  title: string;
  dwellSeconds: number;
  scrollDepthPercent: number;
  isMediaPlaying: boolean;
  timestamp: number;
}

/**
 * Full narrative context payload provided to the AI focus agent.
 */
export interface RollingHistoryWindow {
  sprint: FocusSprint;
  goals?: DecomposedGoal[];
  notes?: SmartPageNote[];
  companionId: OrganismId;
  currentTab: BrowsingBreadcrumb;
  timeline: RollingTimelineEntry[];
  elapsedSprintMinutes: number;
  totalDivergenceCountToday?: number;
  localTime?: string;
  isContinuousFlow?: boolean;
}

/**
 * AI Agent's classification of user activity alignment.
 */
export type AgentFocusStatus =
  | 'on_task'
  | 'exploring_tangent'
  | 'distracted'
  | 'resting_or_idle'
  | 'goal_completed';

/**
 * Structured output generated by the AI evaluation agent.
 */
export interface EvaluationResult {
  status: AgentFocusStatus;
  divergenceScore: number;
  mood: OrganismState;
  remark: string;
  visualEffect: 'none' | 'vignette' | 'screen_shake' | 'confetti';
  soundReaction: 'none' | 'chirp' | 'alert' | 'celebrate' | 'sigh';
  reasoning: string;
}
